### ISSUE TITLE
Symfony 3.0

### ISSUE THREAD

**Issue by hackzilla** [blackknight467/AYAHBundle#4]
Thanks for this bundle, I use it on a few sites.

Currently I'm thinking about Symfony 3.0 is due soon.

There are a couple of issues that Symfony 2.7 has raised.

```
DEPRECATED - blackknight467\AYAHBundle\Type\AYAHType: The FormTypeInterface::setDefaultOptions() method is deprecated since version 2.7 and will be removed in 3.0. Use configureOptions() instead. This method will be added to the FormTypeInterface with Symfony 3.0.

DEPRECATED - Constants PRE_BIND, BIND and POST_BIND in class Symfony\Component\Form\FormEvents are deprecated since version 2.3 and will be removed in 3.0. Use PRE_SUBMIT, SUBMIT and POST_SUBMIT instead.
```

I can do you a pull request if you'd like?

**Comment by blackknight467** [comment]
@hackzilla thanks for bringing these issues up.  If you'd like to submit a pull request i'd be more than happy to accept :)

**Comment by hackzilla** [comment]
I was going to list these as a single PR, but decided against it, because it'll allow you to decide the minimum version of symfony components your happy with.

I figured 2.3 was easy, as anything below is unsupported.
2.7 is a harder call, and probably would be appropriate for a 2.0 tag
